version: '3.8'
services:
  api:
    image: node:18
    container_name: api2
    environment:
      - DB_URL=postgres://romeo:jkljkl@db:5432/colours
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db

  db:
    image: postgres
    container_name: db2
    # ports:
    #   - 5432:5432
    volumes:
      - dbdata2:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=colours
      - POSTGRES_USER=romeo
      - POSTGRES_PASSWORD=jkljkl

volumes:
  dbdata2:
